"""Add brand_id column to products table

Revision ID: 3cab280570b6
Revises: 6efc3153bd83
Create Date: 2025-11-13 10:06:21.513003

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3cab280570b6"
down_revision = "6efc3153bd83"
branch_labels = None
depends_on = None


def upgrade():
    # Simplified migration - only add brand_id to products
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("brand_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_products_brand_id", "brands", ["brand_id"], ["id"]
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.drop_index("idx_movement_warehouse_date")
        batch_op.drop_index("idx_movement_user")
        batch_op.drop_index("idx_movement_type_date")
        batch_op.drop_index("idx_movement_reference")
        batch_op.drop_index("idx_movement_product_date")
        batch_op.create_index(
            batch_op.f("idx_stock_movement_warehouse"),
            ["warehouse_id", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_stock_movement_type"),
            ["movement_type", "created_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_stock_movement_product"),
            ["product_id", "created_at"],
            unique=False,
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("brand_id")

    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.drop_index("idx_image_product")
        batch_op.drop_index("idx_image_primary")
        batch_op.create_index(
            batch_op.f("ix_product_images_created_at"), ["created_at"], unique=False
        )

    with op.batch_alter_table("invoice_payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reference_number", sa.VARCHAR(length=100), nullable=True)
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "unified_invoices", ["invoice_id"], ["id"])
        batch_op.drop_index("idx_invoice_payment_invoice")
        batch_op.drop_index("idx_invoice_payment_date")
        batch_op.alter_column(
            "payment_method",
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=13),
            nullable=False,
        )
        batch_op.alter_column(
            "amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=15, scale=3),
            existing_nullable=False,
        )
        batch_op.drop_column("reference")

    with op.batch_alter_table("brands", schema=None) as batch_op:
        batch_op.drop_index("idx_brand_name_ar")
        batch_op.drop_index("idx_brand_name")
        batch_op.drop_index("idx_brand_active")

    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("warehouse_id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("transaction_type", sa.VARCHAR(length=20), nullable=False),
        sa.Column("quantity_change", sa.INTEGER(), nullable=False),
        sa.Column("quantity_before", sa.INTEGER(), nullable=False),
        sa.Column("quantity_after", sa.INTEGER(), nullable=False),
        sa.Column("reference_type", sa.VARCHAR(length=20), nullable=True),
        sa.Column("reference_id", sa.INTEGER(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("notes_ar", sa.TEXT(), nullable=True),
        sa.Column("timestamp", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_transactions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_warehouse_id"),
            ["warehouse_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_transaction_type"),
            ["transaction_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_timestamp"),
            ["timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_product_id"),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_transaction_warehouse_date"),
            ["warehouse_id", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_transaction_type_date"),
            ["transaction_type", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_transaction_reference"),
            ["reference_type", "reference_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("idx_transaction_product_date"),
            ["product_id", "timestamp"],
            unique=False,
        )

    op.create_table(
        "inventory",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("product_id", sa.INTEGER(), nullable=False),
        sa.Column("warehouse_id", sa.INTEGER(), nullable=False),
        sa.Column("quantity", sa.INTEGER(), nullable=False),
        sa.Column("reserved_quantity", sa.INTEGER(), nullable=True),
        sa.Column("available_quantity", sa.INTEGER(), nullable=True),
        sa.Column("last_updated", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "product_id", "warehouse_id", name=op.f("uq_product_warehouse")
        ),
    )
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_inventory_warehouse_id"), ["warehouse_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_last_updated"), ["last_updated"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_inventory_quantity"), ["quantity"], unique=False
        )
        batch_op.create_index(
            batch_op.f("idx_inventory_product_warehouse"),
            ["product_id", "warehouse_id"],
            unique=False,
        )

    # ### end Alembic commands ###
