/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User login
         * @description Authenticate user and return JWT tokens
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                /** @description Invalid credentials */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Too many failed attempts (account locked) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * User logout
         * @description Revoke JWT tokens and end session
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logout successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh access token
         * @description Get new access token using refresh token
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description Token refreshed successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshResponse"];
                    };
                };
                /** @description Invalid or expired refresh token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Get authenticated user information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User information retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mfa/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup MFA
         * @description Generate QR code for MFA setup
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description MFA setup initiated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MFASetupResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify MFA code
         * @description Verify TOTP code and enable MFA
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MFAVerifyRequest"];
                };
            };
            responses: {
                /** @description MFA verified and enabled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Invalid MFA code */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mfa/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Disable MFA
         * @description Disable MFA for current user
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MFADisableRequest"];
                };
            };
            responses: {
                /** @description MFA disabled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Invalid password */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List products
         * @description Get paginated list of products with filtering and search
         */
        get: {
            parameters: {
                query?: {
                    /** @description Page number */
                    page?: number;
                    /** @description Items per page */
                    per_page?: number;
                    /** @description Search query (name, SKU, barcode) */
                    search?: string;
                    /** @description Filter by category ID */
                    category_id?: number;
                    /** @description Filter by active status */
                    is_active?: boolean;
                    /** @description Show only low stock products */
                    low_stock?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Products retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create product
         * @description Create a new product
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductCreateRequest"];
                };
            };
            responses: {
                /** @description Product created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product by ID
         * @description Get detailed product information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        /**
         * Update product
         * @description Update existing product
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ProductUpdateRequest"];
                };
            };
            responses: {
                /** @description Product updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete product
         * @description Delete a product
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Product ID */
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Product deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Product not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List customers
         * @description Get paginated list of customers with filtering and search
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    /** @description Search query (name, email, phone) */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customers retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create customer
         * @description Create a new customer
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerCreateRequest"];
                };
            };
            responses: {
                /** @description Customer created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Validation error */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Customer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        /** Update customer */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CustomerUpdateRequest"];
                };
            };
            responses: {
                /** @description Customer updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerResponse"];
                    };
                };
                /** @description Customer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        post?: never;
        /** Delete customer */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
                /** @description Customer not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List suppliers
         * @description Get paginated list of suppliers
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Suppliers retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupplierListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create supplier */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SupplierCreateRequest"];
                };
            };
            responses: {
                /** @description Supplier created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupplierResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/suppliers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get supplier by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supplier retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupplierResponse"];
                    };
                };
            };
        };
        /** Update supplier */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SupplierUpdateRequest"];
                };
            };
            responses: {
                /** @description Supplier updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupplierResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete supplier */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supplier deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List invoices
         * @description Get paginated list of invoices with optional filters
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    status?: "draft" | "sent" | "paid" | "overdue" | "cancelled";
                    customer_id?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoices retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create invoice */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InvoiceCreateRequest"];
                };
            };
            responses: {
                /** @description Invoice created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get invoice by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceResponse"];
                    };
                };
            };
        };
        /** Update invoice */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InvoiceUpdateRequest"];
                };
            };
            responses: {
                /** @description Invoice updated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvoiceResponse"];
                    };
                };
            };
        };
        post?: never;
        /** Delete invoice */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download invoice PDF */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF generated successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoices/{id}/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send invoice via email */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invoice sent successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List sales transactions */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    start_date?: string;
                    end_date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SaleListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create sale transaction */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SaleCreateRequest"];
                };
            };
            responses: {
                /** @description Sale created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SaleResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sale by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sale retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SaleResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get sales statistics */
        get: {
            parameters: {
                query?: {
                    start_date?: string;
                    end_date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SaleStatsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List inventory items */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    low_stock?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inventory retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create inventory movement */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["InventoryMovementRequest"];
                };
            };
            responses: {
                /** @description Movement created successfully */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryMovementResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/inventory/low-stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get low stock items */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Low stock items retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dashboard statistics
         * @description Get overview statistics for dashboard
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Statistics retrieved successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DashboardStatsResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sales report
         * @description Get sales report with filters
         */
        get: {
            parameters: {
                query?: {
                    start_date?: string;
                    end_date?: string;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Sales report retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inventory report
         * @description Get inventory status report
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Inventory report retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InventoryReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/financial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Financial report
         * @description Get financial summary report
         */
        get: {
            parameters: {
                query?: {
                    start_date?: string;
                    end_date?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Financial report retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FinancialReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Customer report
         * @description Get customer statistics and activity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer report retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/suppliers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Supplier report
         * @description Get supplier statistics and activity
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Supplier report retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SupplierReportResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List categories
         * @description Get all product categories
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Categories retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create category
         * @description Create new product category
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryCreateRequest"];
                };
            };
            responses: {
                /** @description Category created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get category
         * @description Get category by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
            };
        };
        /**
         * Update category
         * @description Update category details
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CategoryUpdateRequest"];
                };
            };
            responses: {
                /** @description Category updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete category
         * @description Delete category by ID
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users
         * @description Get all users (admin only)
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    per_page?: number;
                    role?: "admin" | "manager" | "user";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Users retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserListResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create user
         * @description Create new user (admin only)
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserCreateRequest"];
                };
            };
            responses: {
                /** @description User created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Get user by ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        /**
         * Update user
         * @description Update user details
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserUpdateRequest"];
                };
            };
            responses: {
                /** @description User updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete user
         * @description Delete user by ID (admin only)
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description User deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Check system health status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthCheckResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * System status
         * @description Get detailed system status
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description System status retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemStatusResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/system/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API version
         * @description Get API version information
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Version information retrieved */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VersionResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessResponse: {
            /** @example true */
            success: boolean;
            /** @example Operation completed successfully */
            message: string;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            traceId: string;
            /** @description Optional response data */
            data?: Record<string, never>;
        };
        ErrorEnvelope: {
            /** @example false */
            success: boolean;
            /**
             * @description Error code for client handling
             * @example AUTH_001
             */
            code: string;
            /** @example Invalid credentials */
            message: string;
            /** @description Optional error details */
            details?: Record<string, never>;
            /**
             * Format: uuid
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            traceId: string;
        };
        LoginRequest: {
            /** @example admin */
            username: string;
            /**
             * Format: password
             * @example admin123
             */
            password: string;
            /**
             * @description TOTP code (required if MFA enabled)
             * @example 123456
             */
            mfa_code?: string;
        };
        LoginResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /** @description JWT access token (15 minutes) */
                access_token: string;
                /** @description JWT refresh token (7 days) */
                refresh_token: string;
                user: components["schemas"]["User"];
            };
        };
        RefreshRequest: {
            /** @description JWT refresh token */
            refresh_token: string;
        };
        RefreshResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /** @description New JWT access token */
                access_token: string;
            };
        };
        UserResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["User"];
        };
        User: {
            /** @example 1 */
            id: number;
            /** @example admin */
            username: string;
            /**
             * Format: email
             * @example admin@gaaragroup.com
             */
            email: string;
            /** @example مدير النظام */
            full_name: string;
            /**
             * @example admin
             * @enum {string}
             */
            role: "admin" | "manager" | "user";
            /** @example false */
            mfa_enabled?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        MFASetupResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /** @description Base64-encoded QR code image */
                qr_code: string;
                /** @description TOTP secret (for manual entry) */
                secret: string;
            };
        };
        MFAVerifyRequest: {
            /** @example 123456 */
            code: string;
        };
        MFADisableRequest: {
            /** Format: password */
            password: string;
        };
        ProductListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items: components["schemas"]["Product"][];
                /** @example 100 */
                total: number;
                /** @example 1 */
                page: number;
                /** @example 20 */
                per_page: number;
                /** @example 5 */
                pages: number;
            };
        };
        ProductResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["Product"];
        };
        Product: {
            /** @example 1 */
            id: number;
            /** @example منتج تجريبي */
            name: string;
            /** @example PROD-001 */
            sku: string;
            /** @example 1234567890123 */
            barcode?: string;
            /** @example وصف المنتج */
            description?: string;
            /**
             * Format: float
             * @example 99.99
             */
            price: number;
            /**
             * Format: float
             * @example 50
             */
            cost?: number;
            /** @example 100 */
            stock_quantity: number;
            /** @example 10 */
            min_stock_level?: number;
            /** @example 1 */
            category_id?: number;
            /** @example true */
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProductCreateRequest: {
            name: string;
            sku: string;
            barcode?: string;
            description?: string;
            /** Format: float */
            price: number;
            /** Format: float */
            cost?: number;
            /** @default 0 */
            stock_quantity: number;
            /** @default 0 */
            min_stock_level: number;
            category_id?: number;
            /** @default true */
            is_active: boolean;
        };
        ProductUpdateRequest: {
            name?: string;
            sku?: string;
            barcode?: string;
            description?: string;
            /** Format: float */
            price?: number;
            /** Format: float */
            cost?: number;
            stock_quantity?: number;
            min_stock_level?: number;
            category_id?: number;
            is_active?: boolean;
        };
        CustomerListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items: components["schemas"]["Customer"][];
                total: number;
                page: number;
                per_page: number;
                pages: number;
            };
        };
        CustomerResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["Customer"];
        };
        Customer: {
            /** @example 1 */
            id: number;
            /** @example عميل تجريبي */
            name: string;
            /**
             * Format: email
             * @example customer@example.com
             */
            email?: string;
            /** @example +966501234567 */
            phone?: string;
            /** @example الرياض، المملكة العربية السعودية */
            address?: string;
            /**
             * Format: float
             * @example 0
             */
            balance?: number;
            /** @example true */
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        CustomerCreateRequest: {
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
            /** @default true */
            is_active: boolean;
        };
        CustomerUpdateRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
            is_active?: boolean;
        };
        SupplierListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items: components["schemas"]["Supplier"][];
                total: number;
                page: number;
                per_page: number;
                pages: number;
            };
        };
        SupplierResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["Supplier"];
        };
        Supplier: {
            /** @example 1 */
            id: number;
            /** @example مورد تجريبي */
            name: string;
            /**
             * Format: email
             * @example supplier@example.com
             */
            email?: string;
            /** @example +966501234567 */
            phone?: string;
            /** @example جدة، المملكة العربية السعودية */
            address?: string;
            /**
             * Format: float
             * @example 0
             */
            balance?: number;
            /** @example true */
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        SupplierCreateRequest: {
            name: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
            /** @default true */
            is_active: boolean;
        };
        SupplierUpdateRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            address?: string;
            is_active?: boolean;
        };
        DashboardStatsResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /** @example 150 */
                total_products?: number;
                /** @example 145 */
                active_products?: number;
                /** @example 50 */
                total_customers?: number;
                /** @example 20 */
                total_suppliers?: number;
                /** @example 500 */
                total_transactions?: number;
                /**
                 * Format: float
                 * @example 50000
                 */
                total_revenue?: number;
                /** @example 5 */
                low_stock_count?: number;
            };
        };
        InvoiceListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items: components["schemas"]["Invoice"][];
                total: number;
                page: number;
                per_page: number;
                pages: number;
            };
        };
        InvoiceResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["Invoice"];
        };
        Invoice: {
            /** @example 1 */
            id: number;
            /** @example INV-2025-001 */
            invoice_number: string;
            /** @example 1 */
            customer_id: number;
            /** @example عميل تجريبي */
            customer_name?: string;
            /**
             * Format: date
             * @example 2025-01-15
             */
            issue_date: string;
            /**
             * Format: date
             * @example 2025-02-15
             */
            due_date?: string;
            /**
             * Format: float
             * @example 1000
             */
            subtotal?: number;
            /**
             * Format: float
             * @example 150
             */
            tax_amount?: number;
            /**
             * Format: float
             * @example 50
             */
            discount_amount?: number;
            /**
             * Format: float
             * @example 1100
             */
            total_amount: number;
            /**
             * Format: float
             * @example 0
             */
            paid_amount?: number;
            /**
             * @example draft
             * @enum {string}
             */
            status: "draft" | "sent" | "paid" | "overdue" | "cancelled";
            /** @example ملاحظات الفاتورة */
            notes?: string;
            items?: components["schemas"]["InvoiceItem"][];
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        InvoiceItem: {
            /** @example 1 */
            id?: number;
            /** @example 1 */
            product_id: number;
            /** @example منتج تجريبي */
            product_name?: string;
            /** @example 5 */
            quantity: number;
            /**
             * Format: float
             * @example 100
             */
            unit_price: number;
            /**
             * Format: float
             * @example 0
             */
            discount?: number;
            /**
             * Format: float
             * @example 15
             */
            tax_rate?: number;
            /**
             * Format: float
             * @example 500
             */
            total: number;
        };
        InvoiceCreateRequest: {
            customer_id: number;
            /** Format: date */
            issue_date: string;
            /** Format: date */
            due_date?: string;
            /**
             * Format: float
             * @default 0
             */
            discount_amount: number;
            notes?: string;
            items: {
                product_id: number;
                quantity: number;
                /** Format: float */
                unit_price: number;
                /**
                 * Format: float
                 * @default 0
                 */
                discount: number;
                /**
                 * Format: float
                 * @default 15
                 */
                tax_rate: number;
            }[];
        };
        InvoiceUpdateRequest: {
            customer_id?: number;
            /** Format: date */
            issue_date?: string;
            /** Format: date */
            due_date?: string;
            /** Format: float */
            discount_amount?: number;
            /** @enum {string} */
            status?: "draft" | "sent" | "paid" | "overdue" | "cancelled";
            notes?: string;
            items?: {
                product_id?: number;
                quantity?: number;
                /** Format: float */
                unit_price?: number;
                /** Format: float */
                discount?: number;
                /** Format: float */
                tax_rate?: number;
            }[];
        };
        SaleListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items: components["schemas"]["Sale"][];
                total: number;
                page: number;
                per_page: number;
                pages: number;
            };
        };
        SaleResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["Sale"];
        };
        Sale: {
            /** @example 1 */
            id: number;
            /**
             * Format: date-time
             * @example 2025-01-15T14:30:00Z
             */
            sale_date: string;
            /** @example 1 */
            customer_id?: number;
            /** @example عميل تجريبي */
            customer_name?: string;
            /**
             * Format: float
             * @example 500
             */
            total_amount: number;
            /**
             * @example cash
             * @enum {string}
             */
            payment_method: "cash" | "card" | "transfer" | "credit";
            /** @example ملاحظات البيع */
            notes?: string;
            items?: {
                product_id?: number;
                product_name?: string;
                quantity?: number;
                /** Format: float */
                unit_price?: number;
                /** Format: float */
                total?: number;
            }[];
        };
        SaleCreateRequest: {
            customer_id?: number;
            /** @enum {string} */
            payment_method: "cash" | "card" | "transfer" | "credit";
            notes?: string;
            items: {
                product_id: number;
                quantity: number;
                /** Format: float */
                unit_price: number;
            }[];
        };
        SaleStatsResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /**
                 * Format: float
                 * @example 50000
                 */
                total_sales?: number;
                /** @example 150 */
                total_transactions?: number;
                /**
                 * Format: float
                 * @example 333.33
                 */
                average_sale?: number;
                top_products?: {
                    product_id?: number;
                    product_name?: string;
                    quantity_sold?: number;
                    /** Format: float */
                    total_revenue?: number;
                }[];
            };
        };
        InventoryListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items: components["schemas"]["InventoryItem"][];
                total: number;
                page: number;
                per_page: number;
                pages: number;
            };
        };
        InventoryItem: {
            /** @example 1 */
            product_id: number;
            /** @example منتج تجريبي */
            product_name: string;
            /** @example PROD-001 */
            sku?: string;
            /** @example 100 */
            current_stock: number;
            /** @example 10 */
            min_stock_level?: number;
            /** @example false */
            is_low_stock?: boolean;
            /** Format: date-time */
            last_movement_date?: string;
        };
        InventoryMovementRequest: {
            product_id: number;
            quantity: number;
            /** @enum {string} */
            movement_type: "in" | "out" | "adjustment";
            reason?: string;
            notes?: string;
        };
        InventoryMovementResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                id?: number;
                product_id?: number;
                quantity?: number;
                movement_type?: string;
                previous_stock?: number;
                new_stock?: number;
                /** Format: date-time */
                created_at?: string;
            };
        };
        SalesReportResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /** Format: float */
                total_sales?: number;
                total_transactions?: number;
                /** Format: float */
                average_transaction?: number;
                top_products?: Record<string, never>[];
            };
        };
        InventoryReportResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                total_items?: number;
                low_stock_items?: number;
                out_of_stock_items?: number;
                /** Format: float */
                total_value?: number;
            };
        };
        FinancialReportResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                /** Format: float */
                total_revenue?: number;
                /** Format: float */
                total_cost?: number;
                /** Format: float */
                gross_profit?: number;
                /** Format: float */
                profit_margin?: number;
            };
        };
        CustomerReportResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                total_customers?: number;
                active_customers?: number;
                /** Format: float */
                total_purchases?: number;
                /** Format: float */
                average_purchase?: number;
            };
        };
        SupplierReportResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                total_suppliers?: number;
                active_suppliers?: number;
                /** Format: float */
                total_purchases?: number;
                /** Format: float */
                average_purchase?: number;
            };
        };
        CategoryListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items?: components["schemas"]["Category"][];
                total?: number;
                page?: number;
                per_page?: number;
                pages?: number;
            };
        };
        Category: {
            id: number;
            /** @example الإلكترونيات */
            name: string;
            description?: string;
            /** @default true */
            is_active: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        CategoryCreateRequest: {
            name: string;
            description?: string;
        };
        CategoryUpdateRequest: {
            name?: string;
            description?: string;
            is_active?: boolean;
        };
        CategoryResponse: components["schemas"]["SuccessResponse"] & {
            data?: components["schemas"]["Category"];
        };
        UserListResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                items?: components["schemas"]["User"][];
                total?: number;
                page?: number;
                per_page?: number;
                pages?: number;
            };
        };
        UserCreateRequest: {
            username: string;
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
            full_name: string;
            /** @enum {string} */
            role: "admin" | "manager" | "user";
            department?: string;
        };
        UserUpdateRequest: {
            /** Format: email */
            email?: string;
            full_name?: string;
            /** @enum {string} */
            role?: "admin" | "manager" | "user";
            department?: string;
            is_active?: boolean;
        };
        HealthCheckResponse: {
            /** @enum {string} */
            status?: "healthy" | "degraded" | "unhealthy";
            /** Format: date-time */
            timestamp?: string;
            version?: string;
        };
        SystemStatusResponse: components["schemas"]["SuccessResponse"] & {
            data?: {
                status?: string;
                database?: string;
                cache?: string;
                uptime_seconds?: number;
            };
        };
        VersionResponse: {
            /** @example 1.7.0 */
            version?: string;
            /** @example 1.7.0 */
            api_version?: string;
            /** @enum {string} */
            environment?: "development" | "staging" | "production";
            /** Format: date-time */
            timestamp?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
