#!/usr/bin/env python3
"""
Global System Project Initializer (v2026.2)
-------------------------------------------
This script initializes a new project structure based on the Global System standards.
It creates the necessary directories, copies template files, and sets up the environment.

Usage:
    python3 init_project_structure.py --name <project_name> --type <project_type>

Project Types:
    - ml: Machine Learning Project (default)
    - web: Web Application
    - scraping: Web Scraping Project
    - bigdata: Big Data / ETL Project
    - full: Full Stack (All components)
"""

import os
import sys
import argparse
import shutil
from pathlib import Path

def create_directory(path):
    """
    Create directory implementation.
    """
    if not os.path.exists(path):
        os.makedirs(path)
        print(f"✅ Created directory: {path}")
    else:
        print(f"ℹ️  Directory already exists: {path}")

def create_file(path, content=""):
    """
    Create file implementation.
    """
    if not os.path.exists(path):
        with open(path, 'w') as f:
            f.write(content)
        print(f"✅ Created file: {path}")
    else:
        print(f"ℹ️  File already exists: {path}")

def init_ml_structure(base_path):
    """
    Init ml structure implementation.
    """
    dirs = [
        "data/raw", "data/processed", "data/external",
        "notebooks/exploration", "notebooks/modeling",
        "src/data", "src/features", "src/models", "src/visualization",
        "models/staging", "models/production",
        "reports/figures",
        "tests"
    ]
    for d in dirs:
        create_directory(os.path.join(base_path, d))
    
    create_file(os.path.join(base_path, "README.md"), "# ML Project\n\nGenerated by Global System Initializer")
    create_file(os.path.join(base_path, "requirements.txt"), "numpy\npandas\nscikit-learn\nmlflow\n")

def init_scraping_structure(base_path):
    """
    Init scraping structure implementation.
    """
    dirs = [
        "spiders", "pipelines", "middleware", "items", "config"
    ]
    for d in dirs:
        create_directory(os.path.join(base_path, "scraping", d))
    
    # Copy Universal Spider templates if available
    src_spider = Path("infrastructure/scraping/spiders/universal_spider.py")
    dst_spider = Path(base_path) / "scraping/spiders/universal_spider.py"
    if src_spider.exists():
        shutil.copy(src_spider, dst_spider)
        print(f"✅ Copied Universal Spider to {dst_spider}")

    # Copy Config
    src_config = Path("infrastructure/scraping/config/targets.yaml")
    dst_config = Path(base_path) / "scraping/config/targets.yaml"
    if src_config.exists():
        shutil.copy(src_config, dst_config)
        print(f"✅ Copied Scraping Config to {dst_config}")

def init_bigdata_structure(base_path):
    """
    Init bigdata structure implementation.
    """
    dirs = [
        "jobs/etl", "jobs/streaming", "conf/spark", "conf/hadoop", "schemas"
    ]
    for d in dirs:
        create_directory(os.path.join(base_path, "big_data", d))

    # Copy Spark Config
    src_conf = Path("infrastructure/big_data/spark/conf/spark-defaults.conf")
    dst_conf = Path(base_path) / "big_data/conf/spark/spark-defaults.conf"
    if src_conf.exists():
        shutil.copy(src_conf, dst_conf)
        print(f"✅ Copied Spark Config to {dst_conf}")

def main():
    """
    Main implementation.
    """
    parser = argparse.ArgumentParser(description="Initialize Global System Project Structure")
    parser.add_argument("--name", required=True, help="Project Name")
    parser.add_argument("--type", default="ml", choices=["ml", "web", "scraping", "bigdata", "full"], help="Project Type")
    
    args = parser.parse_args()
    
    base_path = os.path.join(os.getcwd(), args.name)
    create_directory(base_path)
    
    print(f"🚀 Initializing {args.type} project: {args.name}...")
    
    # Common Structure
    create_directory(os.path.join(base_path, "docs"))
    create_directory(os.path.join(base_path, "scripts"))
    create_file(os.path.join(base_path, "Solution_Trade_off_Log.md"), "# Solution Trade-off Log\n\n| Decision ID | Problem | Option A | Option B | Chosen Option | Rationale (OSF Score) |\n|---|---|---|---|---|---|\n")
    
    if args.type in ["ml", "full"]:
        init_ml_structure(base_path)
    
    if args.type in ["scraping", "full"]:
        init_scraping_structure(base_path)
        
    if args.type in ["bigdata", "full"]:
        init_bigdata_structure(base_path)
        
    print(f"\n✨ Project {args.name} initialized successfully!")
    print(f"📂 Location: {base_path}")

if __name__ == "__main__":
    main()
