"""init constraints & indexes

Revision ID: e593e8338c1e
Revises: 
Create Date: 2025-10-22 14:11:30.053501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e593e8338c1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'audit_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'backup_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'company_settings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_name', sa.String(length=200), nullable=True),
        sa.Column('company_name_en', sa.String(length=200), nullable=True),
        sa.Column('legal_name', sa.String(length=200), nullable=True),
        sa.Column('tax_number', sa.String(length=100), nullable=True),
        sa.Column('commercial_register', sa.String(length=100), nullable=True),
        sa.Column('address', sa.Text(), nullable=True),
        sa.Column('city', sa.String(length=100), nullable=True),
        sa.Column('state', sa.String(length=100), nullable=True),
        sa.Column('country', sa.String(length=50), nullable=True),
        sa.Column('postal_code', sa.String(length=20), nullable=True),
        sa.Column('phone', sa.String(length=50), nullable=True),
        sa.Column('fax', sa.String(length=50), nullable=True),
        sa.Column('email', sa.String(length=200), nullable=True),
        sa.Column('website', sa.String(length=200), nullable=True),
        sa.Column('logo_url', sa.String(length=500), nullable=True),
        sa.Column('currency', sa.String(length=10), nullable=True),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('fiscal_year_start', sa.Date(), nullable=True),
        sa.Column('business_type', sa.String(length=100), nullable=True),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('employee_count', sa.Integer(), nullable=True),
        sa.Column('established_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smtp_server', sa.String(length=200), nullable=True),
    sa.Column('smtp_port', sa.Integer(), nullable=True),
    sa.Column('use_tls', sa.Boolean(), nullable=True),
    sa.Column('use_ssl', sa.Boolean(), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('from_email', sa.String(length=200), nullable=True),
    sa.Column('from_name', sa.String(length=200), nullable=True),
    sa.Column('reply_to', sa.String(length=200), nullable=True),
    sa.Column('max_emails_per_hour', sa.Integer(), nullable=True),
    sa.Column('email_templates', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('license_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('license_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localization_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('configuration', sa.Text(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('dependencies', sa.Text(), nullable=True),
    sa.Column('auto_update', sa.Boolean(), nullable=True),
    sa.Column('license_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name')
    )
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password_min_length', sa.Integer(), nullable=True),
    sa.Column('password_max_length', sa.Integer(), nullable=True),
    sa.Column('password_require_uppercase', sa.Boolean(), nullable=True),
    sa.Column('password_require_lowercase', sa.Boolean(), nullable=True),
    sa.Column('password_require_numbers', sa.Boolean(), nullable=True),
    sa.Column('password_require_symbols', sa.Boolean(), nullable=True),
    sa.Column('password_expiry_days', sa.Integer(), nullable=True),
    sa.Column('password_history_count', sa.Integer(), nullable=True),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=True),
    sa.Column('max_login_attempts', sa.Integer(), nullable=True),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('two_factor_required', sa.Boolean(), nullable=True),
    sa.Column('ip_whitelist_enabled', sa.Boolean(), nullable=True),
    sa.Column('allowed_ip_ranges', sa.Text(), nullable=True),
    sa.Column('security_headers_enabled', sa.Boolean(), nullable=True),
    sa.Column('audit_log_retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=100), nullable=True),
    sa.Column('system_version', sa.String(length=50), nullable=True),
    sa.Column('default_language', sa.String(length=10), nullable=True),
    sa.Column('default_timezone', sa.String(length=50), nullable=True),
    sa.Column('default_currency', sa.String(length=10), nullable=True),
    sa.Column('is_setup_complete', sa.Boolean(), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=True),
    sa.Column('debug_mode', sa.Boolean(), nullable=True),
    sa.Column('custom_settings', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ui_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('customer_payments')
    op.drop_table('sales_invoice_items')
    op.drop_table('warehouses_new')
    op.drop_table('regions')
    op.drop_table('customer_debts')
    op.drop_table('sales_invoices')
    op.drop_table('sales_engineer_payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_engineer_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('sales_engineer_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['sales_engineer_id'], ['sales_engineers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.create_table('sales_invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('sales_engineer_id', sa.INTEGER(), nullable=True),
    sa.Column('invoice_type', sa.VARCHAR(length=6), nullable=True),
    sa.Column('invoice_date', sa.DATETIME(), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('tax_amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('paid_amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('internal_notes', sa.TEXT(), nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sales_engineer_id'], ['sales_engineers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    op.create_table('customer_debts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.VARCHAR(length=9), nullable=True),
    sa.Column('due_date', sa.DATETIME(), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('warehouses_new',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('manager_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('capacity', sa.FLOAT(), nullable=True),
    sa.Column('current_stock', sa.FLOAT(), nullable=True),
    sa.Column('region_id', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('warehouse_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sales_invoice_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=True),
    sa.Column('product_name', sa.VARCHAR(length=200), nullable=False),
    sa.Column('product_code', sa.VARCHAR(length=100), nullable=True),
    sa.Column('quantity', sa.NUMERIC(precision=12, scale=3), nullable=True),
    sa.Column('unit_price', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('discount_rate', sa.FLOAT(), nullable=True),
    sa.Column('discount_amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('total_amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_payments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payment_number', sa.VARCHAR(length=50), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=14, scale=2), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('payment_date', sa.DATETIME(), nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=100), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_number')
    )
    op.drop_table('ui_settings')
    op.drop_table('system_configuration')
    op.drop_table('security_settings')
    op.drop_table('performance_settings')
    op.drop_table('notification_settings')
    op.drop_table('module_settings')
    op.drop_table('maintenance_settings')
    op.drop_table('localization_settings')
    op.drop_table('license_settings')
    op.drop_table('integration_settings')
    op.drop_table('email_settings')
    op.drop_table('custom_settings')
    op.drop_table('company_settings')
    op.drop_table('backup_settings')
    op.drop_table('audit_settings')
    # ### end Alembic commands ###
