"""
### 📊 Logical Chart (Create -> Verify -> Execute)
```mermaid
flowchart TD
    Start([Start]) --> Order[1. Order Requirements]
    Order --> Create[2. Create Artifacts]
    Create --> Verify{3. Verify Success?}
    Verify -- No --> Rollback[Rollback/Fix]
    Rollback --> Create
    Verify -- Yes --> Execute[4. Execute/Deploy]
    Execute --> End([End])
```

### 🔄 Workflow
1.  **Order**: Define prerequisites and inputs.
2.  **Create**: Generate the output (file, data, resource).
3.  **Verify**: Check if the output meets standards (Syntax, Logic, Compliance).
4.  **Execute**: Apply the change or return the result.

### 📥 Imports
os, logging

### 📤 Exports
def generate_tasks(), def verify_tasks(), def main()

### 💡 Example
```python
# Example usage for generate_task_lists.py
# from generate_task_lists import def generate_tasks()
```
"""

#!/usr/bin/env python3
"""
### 📊 Logical Chart (Create -> Verify -> Execute)
```mermaid
flowchart TD
    Start([Start]) --> Order[1. Order Requirements]
    Order --> Create[2. Create Artifacts]
    Create --> Verify{3. Verify Success?}
    Verify -- No --> Rollback[Rollback/Fix]
    Rollback --> Create
    Verify -- Yes --> Execute[4. Execute/Deploy]
    Execute --> End([End])
```

### 🔄 Workflow
1.  **Order**: Identify directories needing TASKS.md.
2.  **Create**: Generate TASKS.md content and write files.
3.  **Verify**: Check if files exist and contain correct headers.
4.  **Execute**: Commit changes (simulated).

### 📥 Imports
os, logging

### 📤 Exports
def generate_tasks(), def verify_tasks()

### 💡 Example
```python
# Example usage for generate_task_lists.py
# from generate_task_lists import generate_tasks
```
"""

import os
import logging

ROOT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

IGNORE_DIRS = {'.git', '__pycache__', '.pytest_cache', 'node_modules', '.venv', 'env'}

def generate_tasks():
    """Step 2: Create Artifacts"""
    logging.info("📝 Generating TASKS.md files...")
    created_files = []
    
    for root, dirs, files in os.walk(ROOT_DIR):
        # Filter ignored dirs in place
        dirs[:] = [d for d in dirs if d not in IGNORE_DIRS]
        
        task_file = os.path.join(root, "TASKS.md")
        
        # Only create if not exists to preserve user data
        if not os.path.exists(task_file):
            try:
                content = f"# 📋 Task List: {os.path.basename(root)}\n\n"
                content += "> **Auto-Generated by Global System Ultimate**: Use this list to track maintenance and updates.\n\n"
                
                if files:
                    content += "## 📂 Files to Maintain\n"
                    for f in sorted(files):
                        if f != "TASKS.md":
                            content += f"- [ ] **{f}**: Verify functionality and update documentation.\n"
                
                content += "\n---\n*Last Updated: Global System Ultimate Synchronized Intelligence Edition*"
                
                with open(task_file, "w") as f:
                    f.write(content)
                created_files.append(task_file)
                logging.info(f"Created: {task_file}")
            except Exception as e:
                logging.error(f"Failed to create {task_file}: {e}")
                
    return created_files

def verify_tasks(target_files):
    """Step 3: Verify Success"""
    logging.info("🔍 Verifying TASKS.md files...")
    failed = []
    
    for file_path in target_files:
        if not os.path.exists(file_path):
            failed.append(file_path)
        else:
            # Check content integrity
            with open(file_path, "r") as f:
                if "# 📋 Task List" not in f.read():
                    failed.append(file_path)
                    
    if failed:
        logging.error(f"❌ Verification Failed for: {failed}")
        return False
    
    logging.info("✅ Verification Passed.")
    return True

def main():
    # Step 1: Order (Implicit)
    
    # Step 2: Create
    created = generate_tasks()
    
    if not created:
        logging.info("No new task lists needed.")
        return

    # Step 3: Verify
    if not verify_tasks(created):
        logging.warning("⚠️  Verification failed. Retrying...")
        generate_tasks() # Retry
        if not verify_tasks(created):
            logging.critical("❌ Critical Failure.")
            return

    # Step 4: Execute
    logging.info("🚀 Task Lists Generated Successfully.")

if __name__ == "__main__":
    main()
