"""
### 📊 Logical Chart (Create -> Verify -> Execute)
```mermaid
flowchart TD
    Start([Start]) --> Order[1. Order Requirements]
    Order --> Create[2. Create Artifacts]
    Create --> Verify{3. Verify Success?}
    Verify -- No --> Rollback[Rollback/Fix]
    Rollback --> Create
    Verify -- Yes --> Execute[4. Execute/Deploy]
    Execute --> End([End])
```

### 🔄 Workflow
1.  **Order**: Define prerequisites and inputs.
2.  **Create**: Generate the output (file, data, resource).
3.  **Verify**: Check if the output meets standards (Syntax, Logic, Compliance).
4.  **Execute**: Apply the change or return the result.

### 📥 Imports
os, sys, stat

### 📤 Exports
def install_hooks()

### 💡 Example
```python
# Example usage for git_hooks.py
# from git_hooks import def install_hooks()
```
"""

#!/usr/bin/env python3
"""
Module: git_hooks.py

---
### 🔄 Workflow
1. Initialize module.
    2. Process inputs.
    3. Return results.

### 📊 Logical Chart
```mermaid
    graph TD
        A[Start] --> B{Process}
        B -->|Success| C[End]
    ```

### 📥 Imports
- os
    - sys
    - stat

### 📤 Exports
- Function: install_hooks

### 💡 Examples
```python
    # Example usage
    from git_hooks import install_hooks
    result = install_hooks()
    print(result)
    ```
"""


"""
Git Hooks Manager (Global System Ultimate)
Installs and manages Git hooks for automated documentation and verification.
"""

import os
import sys
import stat

HOOKS_DIR = ".git/hooks"
PRE_COMMIT_HOOK = """#!/bin/sh
# Auto-generated by Global AI System Global System Ultimate
echo "🤖 Running Pre-Commit Checks..."

# 1. Run Sentinel
python3 global/tools/sentinel.py
if [ $? -ne 0 ]; then
    echo "❌ Sentinel Checks Failed! Commit aborted."
    exit 1
fi

# 2. Update Documentation
echo "📚 Updating Documentation..."
python3 global/tools/doc_updater.py .
git add README.md

echo "✅ Pre-Commit Checks Passed."
exit 0
"""

def install_hooks(project_path):
    hooks_path = os.path.join(project_path, HOOKS_DIR)
    if not os.path.exists(hooks_path):
        print(f"⚠️  .git directory not found in {project_path}. Skipping hooks.")
        return

    pre_commit_path = os.path.join(hooks_path, "pre-commit")
    
    with open(pre_commit_path, "w") as f:
        f.write(PRE_COMMIT_HOOK)
    
    # Make executable
    st = os.stat(pre_commit_path)
    os.chmod(pre_commit_path, st.st_mode | stat.S_IEXEC)
    
    print(f"✅ Installed pre-commit hook in {project_path}")

if __name__ == "__main__":
    path = sys.argv[1] if len(sys.argv) > 1 else "."
    install_hooks(path)