"""Add Brand, ProductImage, StockMovement models

Revision ID: 6efc3153bd83
Revises:
Create Date: 2025-11-13 09:00:42.041852

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6efc3153bd83"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("name_ar", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("description_ar", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("brands", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_brands_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_brands_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_brands_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_brands_name_ar"), ["name_ar"], unique=False
        )

    op.create_table(
        "inventory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=True),
        sa.Column("available_quantity", sa.Integer(), nullable=True),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "warehouse_id", name="uq_product_warehouse"),
    )
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.create_index(
            "idx_inventory_product_warehouse",
            ["product_id", "warehouse_id"],
            unique=False,
        )
        batch_op.create_index("idx_inventory_quantity", ["quantity"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_inventory_last_updated"), ["last_updated"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_warehouse_id"), ["warehouse_id"], unique=False
        )

    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("transaction_type", sa.String(length=20), nullable=False),
        sa.Column("quantity_change", sa.Integer(), nullable=False),
        sa.Column("quantity_before", sa.Integer(), nullable=False),
        sa.Column("quantity_after", sa.Integer(), nullable=False),
        sa.Column("reference_type", sa.String(length=20), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("notes_ar", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("inventory_transactions", schema=None) as batch_op:
        batch_op.create_index(
            "idx_transaction_product_date", ["product_id", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_transaction_reference",
            ["reference_type", "reference_id"],
            unique=False,
        )
        batch_op.create_index(
            "idx_transaction_type_date", ["transaction_type", "timestamp"], unique=False
        )
        batch_op.create_index(
            "idx_transaction_warehouse_date",
            ["warehouse_id", "timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_product_id"),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_timestamp"),
            ["timestamp"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_transaction_type"),
            ["transaction_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_inventory_transactions_warehouse_id"),
            ["warehouse_id"],
            unique=False,
        )

    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column(
            "invoice_type",
            sa.Enum(
                "SALES",
                "PURCHASE",
                "SALES_RETURN",
                "PURCHASE_RETURN",
                name="invoicetype",
            ),
            nullable=False,
        ),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("supplier_id", sa.Integer(), nullable=True),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("tax_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("discount_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("shipping_cost", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("other_charges", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("paid_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("remaining_amount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("discount_type", sa.String(length=20), nullable=True),
        sa.Column("discount_value", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("is_tax_inclusive", sa.Boolean(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("exchange_rate", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "CONFIRMED",
                "PAID",
                "PARTIAL",
                "CANCELLED",
                "OVERDUE",
                name="invoicestatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "payment_status",
            sa.Enum("UNPAID", "PARTIAL", "PAID", name="paymentstatus"),
            nullable=True,
        ),
        sa.Column("payment_method", sa.String(length=50), nullable=True),
        sa.Column("payment_terms", sa.String(length=100), nullable=True),
        sa.Column("shipping_address", sa.Text(), nullable=True),
        sa.Column("shipping_method", sa.String(length=50), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("internal_notes", sa.Text(), nullable=True),
        sa.Column("terms_conditions", sa.Text(), nullable=True),
        sa.Column("reference_number", sa.String(length=50), nullable=True),
        sa.Column("po_number", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("paid_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invoice_number"),
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index("idx_invoice_customer", ["customer_id"], unique=False)
        batch_op.create_index("idx_invoice_date", ["invoice_date"], unique=False)
        batch_op.create_index("idx_invoice_number", ["invoice_number"], unique=False)
        batch_op.create_index("idx_invoice_status", ["status"], unique=False)
        batch_op.create_index("idx_invoice_supplier", ["supplier_id"], unique=False)
        batch_op.create_index("idx_invoice_type", ["invoice_type"], unique=False)
        batch_op.create_index("idx_invoice_warehouse", ["warehouse_id"], unique=False)

    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("image_url", sa.String(length=255), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=255), nullable=True),
        sa.Column("medium_url", sa.String(length=255), nullable=True),
        sa.Column("large_url", sa.String(length=255), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column("alt_text_ar", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_product_images_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_product_images_product_id"), ["product_id"], unique=False
        )

    op.create_table(
        "stock_movements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=False),
        sa.Column("movement_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("quantity_before", sa.Integer(), nullable=False),
        sa.Column("quantity_after", sa.Integer(), nullable=False),
        sa.Column("reference_type", sa.String(length=50), nullable=True),
        sa.Column("reference_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("notes_ar", sa.Text(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.create_index(
            "idx_stock_movement_product", ["product_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "idx_stock_movement_type", ["movement_type", "created_at"], unique=False
        )
        batch_op.create_index(
            "idx_stock_movement_warehouse", ["warehouse_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_movement_type"),
            ["movement_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_product_id"), ["product_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_user_id"), ["user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_stock_movements_warehouse_id"),
            ["warehouse_id"],
            unique=False,
        )

    op.create_table(
        "invoice_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.Column("product_name", sa.String(length=200), nullable=True),
        sa.Column("product_sku", sa.String(length=100), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=15, scale=3), nullable=False),
        sa.Column("price", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("discount", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("tax", sa.Numeric(precision=15, scale=2), nullable=True),
        sa.Column("total", sa.Numeric(precision=15, scale=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("invoice_items", schema=None) as batch_op:
        batch_op.create_index("idx_invoice_item_invoice", ["invoice_id"], unique=False)
        batch_op.create_index("idx_invoice_item_product", ["product_id"], unique=False)

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name_ar", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("description_ar", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column("sort_order", sa.Integer(), nullable=True, server_default="0")
        )
        batch_op.create_index(
            "idx_category_parent_active", ["parent_id", "is_active"], unique=False
        )
        batch_op.create_index(
            "idx_category_sort_active", ["sort_order", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_categories_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_categories_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_categories_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_categories_name_ar"), ["name_ar"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_categories_parent_id"), ["parent_id"], unique=False
        )

    with op.batch_alter_table("invoice_payments", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("reference", sa.String(length=100), nullable=True)
        )
        batch_op.alter_column(
            "amount",
            existing_type=sa.NUMERIC(precision=15, scale=3),
            type_=sa.Numeric(precision=15, scale=2),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "payment_method",
            existing_type=sa.VARCHAR(length=13),
            type_=sa.String(length=50),
            nullable=True,
        )
        batch_op.create_index(
            "idx_invoice_payment_date", ["payment_date"], unique=False
        )
        batch_op.create_index(
            "idx_invoice_payment_invoice", ["invoice_id"], unique=False
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            None, "invoices", ["invoice_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name_ar", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("description_ar", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "price",
                sa.Numeric(precision=10, scale=2),
                nullable=True,
                server_default="0",
            )
        )
        batch_op.add_column(
            sa.Column("cost", sa.Numeric(precision=10, scale=2), nullable=True)
        )
        batch_op.add_column(sa.Column("supplier_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("brand_id", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("unit_of_measure", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(
            sa.Column("unit_of_measure_ar", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("reorder_point", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("weight", sa.Numeric(precision=8, scale=3), nullable=True)
        )
        batch_op.add_column(
            sa.Column("dimensions", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(
            sa.Column("image_url", sa.String(length=255), nullable=True)
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=200),
            type_=sa.String(length=100),
            existing_nullable=False,
        )
        batch_op.alter_column("category_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.create_index(
            "idx_product_category_active", ["category_id", "is_active"], unique=False
        )
        batch_op.create_index(
            "idx_product_price_range", ["price", "is_active"], unique=False
        )
        batch_op.create_index(
            "idx_product_stock_level", ["min_stock_level", "is_active"], unique=False
        )
        batch_op.create_index(
            "idx_product_supplier_active", ["supplier_id", "is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_brand_id"), ["brand_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_products_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_products_name_ar"), ["name_ar"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_products_supplier_id"), ["supplier_id"], unique=False
        )
        batch_op.create_foreign_key(None, "brands", ["brand_id"], ["id"])
        batch_op.create_foreign_key(None, "suppliers", ["supplier_id"], ["id"])

    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.add_column(sa.Column("name_ar", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("address_ar", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("is_default", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("updated_at", sa.DateTime(), nullable=True))
        batch_op.alter_column(
            "code", existing_type=sa.VARCHAR(length=20), nullable=False
        )
        batch_op.create_index(batch_op.f("ix_warehouses_code"), ["code"], unique=True)
        batch_op.create_index(
            batch_op.f("ix_warehouses_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_warehouses_is_active"), ["is_active"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_warehouses_manager_id"), ["manager_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_warehouses_name"), ["name"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_warehouses_name_ar"), ["name_ar"], unique=False
        )
        batch_op.create_foreign_key(None, "users", ["manager_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_warehouses_name_ar"))
        batch_op.drop_index(batch_op.f("ix_warehouses_name"))
        batch_op.drop_index(batch_op.f("ix_warehouses_manager_id"))
        batch_op.drop_index(batch_op.f("ix_warehouses_is_active"))
        batch_op.drop_index(batch_op.f("ix_warehouses_created_at"))
        batch_op.drop_index(batch_op.f("ix_warehouses_code"))
        batch_op.alter_column(
            "code", existing_type=sa.VARCHAR(length=20), nullable=True
        )
        batch_op.drop_column("updated_at")
        batch_op.drop_column("is_default")
        batch_op.drop_column("address_ar")
        batch_op.drop_column("name_ar")

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_products_supplier_id"))
        batch_op.drop_index(batch_op.f("ix_products_name_ar"))
        batch_op.drop_index(batch_op.f("ix_products_name"))
        batch_op.drop_index(batch_op.f("ix_products_is_active"))
        batch_op.drop_index(batch_op.f("ix_products_created_at"))
        batch_op.drop_index(batch_op.f("ix_products_category_id"))
        batch_op.drop_index(batch_op.f("ix_products_brand_id"))
        batch_op.drop_index("idx_product_supplier_active")
        batch_op.drop_index("idx_product_stock_level")
        batch_op.drop_index("idx_product_price_range")
        batch_op.drop_index("idx_product_category_active")
        batch_op.alter_column("category_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=100),
            type_=sa.VARCHAR(length=200),
            existing_nullable=False,
        )
        batch_op.drop_column("image_url")
        batch_op.drop_column("dimensions")
        batch_op.drop_column("weight")
        batch_op.drop_column("reorder_point")
        batch_op.drop_column("unit_of_measure_ar")
        batch_op.drop_column("unit_of_measure")
        batch_op.drop_column("brand_id")
        batch_op.drop_column("supplier_id")
        batch_op.drop_column("cost")
        batch_op.drop_column("price")
        batch_op.drop_column("description_ar")
        batch_op.drop_column("name_ar")

    with op.batch_alter_table("invoice_payments", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "unified_invoices", ["invoice_id"], ["id"])
        batch_op.drop_index("idx_invoice_payment_invoice")
        batch_op.drop_index("idx_invoice_payment_date")
        batch_op.alter_column(
            "payment_method",
            existing_type=sa.String(length=50),
            type_=sa.VARCHAR(length=13),
            nullable=False,
        )
        batch_op.alter_column(
            "amount",
            existing_type=sa.Numeric(precision=15, scale=2),
            type_=sa.NUMERIC(precision=15, scale=3),
            existing_nullable=False,
        )
        batch_op.drop_column("reference")

    with op.batch_alter_table("categories", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_categories_parent_id"))
        batch_op.drop_index(batch_op.f("ix_categories_name_ar"))
        batch_op.drop_index(batch_op.f("ix_categories_name"))
        batch_op.drop_index(batch_op.f("ix_categories_is_active"))
        batch_op.drop_index(batch_op.f("ix_categories_created_at"))
        batch_op.drop_index("idx_category_sort_active")
        batch_op.drop_index("idx_category_parent_active")
        batch_op.drop_column("sort_order")
        batch_op.drop_column("description_ar")
        batch_op.drop_column("name_ar")

    with op.batch_alter_table("invoice_items", schema=None) as batch_op:
        batch_op.drop_index("idx_invoice_item_product")
        batch_op.drop_index("idx_invoice_item_invoice")

    op.drop_table("invoice_items")
    with op.batch_alter_table("stock_movements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stock_movements_warehouse_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_user_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_product_id"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_movement_type"))
        batch_op.drop_index(batch_op.f("ix_stock_movements_created_at"))
        batch_op.drop_index("idx_stock_movement_warehouse")
        batch_op.drop_index("idx_stock_movement_type")
        batch_op.drop_index("idx_stock_movement_product")

    op.drop_table("stock_movements")
    with op.batch_alter_table("product_images", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_product_images_product_id"))
        batch_op.drop_index(batch_op.f("ix_product_images_created_at"))

    op.drop_table("product_images")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index("idx_invoice_warehouse")
        batch_op.drop_index("idx_invoice_type")
        batch_op.drop_index("idx_invoice_supplier")
        batch_op.drop_index("idx_invoice_status")
        batch_op.drop_index("idx_invoice_number")
        batch_op.drop_index("idx_invoice_date")
        batch_op.drop_index("idx_invoice_customer")

    op.drop_table("invoices")
    with op.batch_alter_table("inventory_transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_warehouse_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_user_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_transaction_type"))
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_timestamp"))
        batch_op.drop_index(batch_op.f("ix_inventory_transactions_product_id"))
        batch_op.drop_index("idx_transaction_warehouse_date")
        batch_op.drop_index("idx_transaction_type_date")
        batch_op.drop_index("idx_transaction_reference")
        batch_op.drop_index("idx_transaction_product_date")

    op.drop_table("inventory_transactions")
    with op.batch_alter_table("inventory", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_inventory_warehouse_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_product_id"))
        batch_op.drop_index(batch_op.f("ix_inventory_last_updated"))
        batch_op.drop_index("idx_inventory_quantity")
        batch_op.drop_index("idx_inventory_product_warehouse")

    op.drop_table("inventory")
    with op.batch_alter_table("brands", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_brands_name_ar"))
        batch_op.drop_index(batch_op.f("ix_brands_name"))
        batch_op.drop_index(batch_op.f("ix_brands_is_active"))
        batch_op.drop_index(batch_op.f("ix_brands_created_at"))

    op.drop_table("brands")
    # ### end Alembic commands ###
